package ch.bfh.ti.proj1.battleship.frame;

/**
 * 
 * @author L1r
 */
public class NetworkFrame extends javax.swing.JFrame {

	/** Creates new form NewJFrame */
	public NetworkFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButtonCancel = new javax.swing.JButton();
		jButtonConnect = new javax.swing.JButton();
		jLabelStep1of2 = new javax.swing.JLabel();
		jPanelHostOrJoinGame = new javax.swing.JPanel();
		jPanelHostGame = new javax.swing.JPanel();
		jLabelFreePort = new javax.swing.JLabel();
		jLabelHostGame = new javax.swing.JLabel();
		jTextFieldFreePort = new javax.swing.JTextField();
		jRadioButtonHostGame = new javax.swing.JRadioButton();
		jPanelJoinGame = new javax.swing.JPanel();
		jRadioButtonJoinGame = new javax.swing.JRadioButton();
		jLabelJoinGame = new javax.swing.JLabel();
		jLabelSharedPort = new javax.swing.JLabel();
		jTextFieldSharedPort = new javax.swing.JTextField();
		jLabeIPAddress = new javax.swing.JLabel();
		jTextFieldIPAddress = new javax.swing.JTextField();
		jLabelHostOrJoinGame = new javax.swing.JLabel();
		jPanelEnterYourName = new javax.swing.JPanel();
		jTextPlayerName = new javax.swing.JTextField();
		jLabelEnterYourName = new javax.swing.JLabel();
		jLabelPlayerName = new javax.swing.JLabel();
		jLabelStatus = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Battle ship");
		setName("FrameCoordinateGameSettings"); // NOI18N

		jButtonCancel.setText("Cancel");
		jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCancelActionPerformed(evt);
			}
		});

		jButtonConnect.setText("connect");
		jButtonConnect.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonConnectMouseClicked(evt);
			}
		});
		jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonConnectActionPerformed(evt);
			}
		});

		jLabelStep1of2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabelStep1of2.setText("Step 1/2 - Establish network connection");

		jPanelHostOrJoinGame.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		jPanelHostGame
				.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabelFreePort.setText("Free Port");

		jLabelHostGame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelHostGame.setText("Host a new game:");

		jTextFieldFreePort.setText("4444");
		jTextFieldFreePort
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jTextFieldFreePortActionPerformed(evt);
					}
				});

		jRadioButtonHostGame.setSelected(true);
		jRadioButtonHostGame.setToolTipText("Tooltip");
		jRadioButtonHostGame
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonHostGameActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout jPanelHostGameLayout = new javax.swing.GroupLayout(
				jPanelHostGame);
		jPanelHostGame.setLayout(jPanelHostGameLayout);
		jPanelHostGameLayout
				.setHorizontalGroup(jPanelHostGameLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelHostGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelHostGameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelHostGameLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabelHostGame)
																		.addGap(26,
																				26,
																				26)
																		.addComponent(
																				jRadioButtonHostGame))
														.addGroup(
																jPanelHostGameLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabelFreePort)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				52,
																				Short.MAX_VALUE)
																		.addComponent(
																				jTextFieldFreePort,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				77,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		jPanelHostGameLayout
				.setVerticalGroup(jPanelHostGameLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelHostGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelHostGameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabelHostGame)
														.addComponent(
																jRadioButtonHostGame))
										.addGap(25, 25, 25)
										.addGroup(
												jPanelHostGameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabelFreePort)
														.addComponent(
																jTextFieldFreePort,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(52, Short.MAX_VALUE)));

		jPanelJoinGame
				.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jRadioButtonJoinGame.setToolTipText("Tooltip");
		jRadioButtonJoinGame
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jRadioButtonJoinGameActionPerformed(evt);
					}
				});

		jLabelJoinGame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelJoinGame.setText("Join a hosted game:");

		jLabelSharedPort.setText("Shared Port of Host");

		jTextFieldSharedPort.setText("4444");
		jTextFieldSharedPort.setEnabled(false);

		jLabeIPAddress.setText("IP-Address of Host");

		jTextFieldIPAddress.setText("localhost");
		jTextFieldIPAddress.setEnabled(false);

		javax.swing.GroupLayout jPanelJoinGameLayout = new javax.swing.GroupLayout(
				jPanelJoinGame);
		jPanelJoinGame.setLayout(jPanelJoinGameLayout);
		jPanelJoinGameLayout
				.setHorizontalGroup(jPanelJoinGameLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelJoinGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelJoinGameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelJoinGameLayout
																		.createSequentialGroup()
																		.addGroup(
																				jPanelJoinGameLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabelSharedPort)
																						.addComponent(
																								jLabeIPAddress))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				jPanelJoinGameLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextFieldIPAddress,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								84,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextFieldSharedPort,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								84,
																								Short.MAX_VALUE)))
														.addGroup(
																jPanelJoinGameLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabelJoinGame)
																		.addGap(29,
																				29,
																				29)
																		.addComponent(
																				jRadioButtonJoinGame)))
										.addContainerGap()));
		jPanelJoinGameLayout
				.setVerticalGroup(jPanelJoinGameLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelJoinGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelJoinGameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabelJoinGame)
														.addComponent(
																jRadioButtonJoinGame,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																21,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(25, 25, 25)
										.addGroup(
												jPanelJoinGameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabelSharedPort)
														.addComponent(
																jTextFieldSharedPort,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanelJoinGameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabeIPAddress)
														.addComponent(
																jTextFieldIPAddress,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jLabelHostOrJoinGame.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelHostOrJoinGame
				.setText("Would you like to host a game or to join a hosted game?");

		javax.swing.GroupLayout jPanelHostOrJoinGameLayout = new javax.swing.GroupLayout(
				jPanelHostOrJoinGame);
		jPanelHostOrJoinGame.setLayout(jPanelHostOrJoinGameLayout);
		jPanelHostOrJoinGameLayout
				.setHorizontalGroup(jPanelHostOrJoinGameLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelHostOrJoinGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelHostOrJoinGameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelHostOrJoinGameLayout
																		.createSequentialGroup()
																		.addComponent(
																				jPanelHostGame,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jPanelJoinGame,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jLabelHostOrJoinGame))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanelHostOrJoinGameLayout
				.setVerticalGroup(jPanelHostOrJoinGameLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanelHostOrJoinGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabelHostOrJoinGame)
										.addGap(18, 18, 18)
										.addGroup(
												jPanelHostOrJoinGameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanelHostGame,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanelJoinGame,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));

		jPanelEnterYourName.setBorder(javax.swing.BorderFactory
				.createEtchedBorder());

		jTextPlayerName.setText("Player");
		jTextPlayerName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextPlayerNameActionPerformed(evt);
			}
		});

		jLabelEnterYourName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabelEnterYourName.setText("Please enter your name:");

		jLabelPlayerName.setText("Player's Name");

		javax.swing.GroupLayout jPanelEnterYourNameLayout = new javax.swing.GroupLayout(
				jPanelEnterYourName);
		jPanelEnterYourName.setLayout(jPanelEnterYourNameLayout);
		jPanelEnterYourNameLayout
				.setHorizontalGroup(jPanelEnterYourNameLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelEnterYourNameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelEnterYourNameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabelEnterYourName)
														.addGroup(
																jPanelEnterYourNameLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabelPlayerName)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jTextPlayerName,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				113,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(249, Short.MAX_VALUE)));
		jPanelEnterYourNameLayout
				.setVerticalGroup(jPanelEnterYourNameLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelEnterYourNameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabelEnterYourName)
										.addGap(18, 18, 18)
										.addGroup(
												jPanelEnterYourNameLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabelPlayerName)
														.addComponent(
																jTextPlayerName,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jLabelStatus
				.setText("Connecting...Please start application of second player if it is not started yet.");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(20, 20,
																		20)
																.addComponent(
																		jLabelStep1of2))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						jPanelEnterYourName,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jPanelHostOrJoinGame,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jButtonConnect,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		214,
																		Short.MAX_VALUE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButtonCancel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		229,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabelStatus)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabelStep1of2)
								.addGap(18, 18, 18)
								.addComponent(jPanelEnterYourName,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jPanelHostOrJoinGame,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jLabelStatus)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButtonConnect)
												.addComponent(jButtonCancel))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jTextPlayerNameActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextFieldFreePortActionPerformed(
			java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jRadioButtonHostGameActionPerformed(
			java.awt.event.ActionEvent evt) {
		jRadioButtonJoinGame.setSelected(false);
		jRadioButtonHostGame.setSelected(true);

		jTextFieldFreePort.setEnabled(true);
		jTextFieldIPAddress.setEnabled(false);
		jTextFieldSharedPort.setEnabled(false);
	}

	private void jRadioButtonJoinGameActionPerformed(
			java.awt.event.ActionEvent evt) {
		jRadioButtonHostGame.setSelected(false);
		jRadioButtonJoinGame.setSelected(true);

		jTextFieldFreePort.setEnabled(false);
		jTextFieldIPAddress.setEnabled(true);
		jTextFieldSharedPort.setEnabled(true);
	}

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {
		System.exit(0);
	}

	private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {
	}

	private void jButtonConnectMouseClicked(java.awt.event.MouseEvent evt) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CoordinateFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CoordinateFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CoordinateFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CoordinateFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new CoordinateFrame().setVisible(true);
			}
		});
		this.dispose();

	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButtonCancel;
	private javax.swing.JButton jButtonConnect;
	private javax.swing.JLabel jLabeIPAddress;
	private javax.swing.JLabel jLabelEnterYourName;
	private javax.swing.JLabel jLabelFreePort;
	private javax.swing.JLabel jLabelHostGame;
	private javax.swing.JLabel jLabelHostOrJoinGame;
	private javax.swing.JLabel jLabelJoinGame;
	private javax.swing.JLabel jLabelPlayerName;
	private javax.swing.JLabel jLabelSharedPort;
	private javax.swing.JLabel jLabelStatus;
	private javax.swing.JLabel jLabelStep1of2;
	private javax.swing.JPanel jPanelEnterYourName;
	private javax.swing.JPanel jPanelHostGame;
	private javax.swing.JPanel jPanelHostOrJoinGame;
	private javax.swing.JPanel jPanelJoinGame;
	private javax.swing.JRadioButton jRadioButtonHostGame;
	private javax.swing.JRadioButton jRadioButtonJoinGame;
	private javax.swing.JTextField jTextFieldFreePort;
	private javax.swing.JTextField jTextFieldIPAddress;
	private javax.swing.JTextField jTextFieldSharedPort;
	private javax.swing.JTextField jTextPlayerName;
	// End of variables declaration
}
