package ch.bfh.ti.proj1.battleship.frame;

import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 * @author Daniel Kotlàris
 * @author Michael Leiser
 */
public class NetworkFrame extends JFrame {

	// Variables declaration - do not modify
	private JLabel jLabelStep1of2;

	private JPanel jPanelEnterYourName;
	private JLabel jLabelEnterYourName;
	private JLabel jLabelPlayerName;
	private JTextField jTextPlayerName;

	private JPanel jPanelHostOrJoinGame;
	private JLabel jLabelHostOrJoinGame;

	private JPanel jPanelHostGame;
	private JLabel jLabelHostGame;
	private JRadioButton jRadioButtonHostGame;
	private JLabel jLabelFreePort;
	private JTextField jTextFieldFreePort;

	private JPanel jPanelJoinGame;
	private JLabel jLabelJoinGame;
	private JRadioButton jRadioButtonJoinGame;
	private JLabel jLabelSharedPort;
	private JTextField jTextFieldSharedPort;
	private JLabel jLabeIPAddress;
	private JTextField jTextFieldIPAddress;

	private JLabel jLabelStatus;

	private JButton jButtonConnect;
	private JButton jButtonCancel;

	// End of variables declaration

	/** Creates new form NewJFrame */
	public NetworkFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabelStep1of2 = new JLabel();
		jLabelStep1of2.setFont(new Font("Tahoma", 0, 24)); // NOI18N
		jLabelStep1of2.setText("Step 1/2 - Establish network connection");

		jPanelEnterYourName = new JPanel();
		jPanelEnterYourName.setBorder(BorderFactory.createEtchedBorder());
		jLabelEnterYourName = new JLabel();
		jLabelEnterYourName.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabelEnterYourName.setText("Please enter your name:");
		jLabelPlayerName = new JLabel();
		jLabelPlayerName.setText("Player's Name");
		jTextPlayerName = new JTextField();
		jTextPlayerName.setText("Player");

		jPanelHostOrJoinGame = new JPanel();
		jPanelHostOrJoinGame.setBorder(BorderFactory.createEtchedBorder());
		jLabelHostOrJoinGame = new JLabel();
		jLabelHostOrJoinGame.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabelHostOrJoinGame
				.setText("Would you like to host a game or to join a hosted game?");

		jPanelHostGame = new JPanel();
		jPanelHostGame.setBorder(BorderFactory.createEtchedBorder());
		jLabelHostGame = new JLabel();
		jLabelHostGame.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabelHostGame.setText("Host a new game:");
		jRadioButtonHostGame = new JRadioButton();
		jRadioButtonHostGame.setSelected(true);
		jRadioButtonHostGame.setToolTipText("Tooltip");
		jRadioButtonHostGame.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jRadioButtonHostGameActionPerformed(evt);
			}
		});
		jLabelFreePort = new JLabel();
		jLabelFreePort.setText("Free Port");
		jTextFieldFreePort = new JTextField();
		jTextFieldFreePort.setText("4444");

		jPanelJoinGame = new JPanel();
		jPanelJoinGame.setBorder(BorderFactory.createEtchedBorder());
		jLabelJoinGame = new JLabel();
		jLabelJoinGame.setFont(new Font("Tahoma", 1, 11)); // NOI18N
		jLabelJoinGame.setText("Join a hosted game:");
		jRadioButtonJoinGame = new JRadioButton();
		jRadioButtonJoinGame.setToolTipText("Tooltip");
		jRadioButtonJoinGame.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jRadioButtonJoinGameActionPerformed(evt);
			}
		});
		jLabelSharedPort = new JLabel();
		jLabelSharedPort.setText("Shared Port of Host");
		jTextFieldSharedPort = new JTextField();
		jTextFieldSharedPort.setText("4444");
		jTextFieldSharedPort.setEnabled(false);
		jLabeIPAddress = new JLabel();
		jLabeIPAddress.setText("IP-Address of Host");
		jTextFieldIPAddress = new JTextField();
		jTextFieldIPAddress.setText("localhost");
		jTextFieldIPAddress.setEnabled(false);
		jLabelStatus = new JLabel();
		jLabelStatus
				.setText("Connecting...Please start application of second player if it is not started yet.");

	
		jButtonConnect = new JButton();
		jButtonConnect.setText("connect");
		jButtonConnect.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButtonConnectActionPerformed(evt);
			}
		});
		jButtonCancel = new JButton();
		jButtonCancel.setText("Cancel");
		jButtonCancel.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jButtonCancelActionPerformed(evt);
			}
		});

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		setTitle("Battle ship");
		setName("FrameCoordinateGameSettings"); // NOI18N

		GroupLayout jPanelHostGameLayout = new GroupLayout(jPanelHostGame);
		jPanelHostGame.setLayout(jPanelHostGameLayout);
		jPanelHostGameLayout
				.setHorizontalGroup(jPanelHostGameLayout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelHostGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelHostGameLayout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelHostGameLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabelHostGame)
																		.addGap(26,
																				26,
																				26)
																		.addComponent(
																				jRadioButtonHostGame))
														.addGroup(
																jPanelHostGameLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabelFreePort)
																		.addPreferredGap(
																				LayoutStyle.ComponentPlacement.RELATED,
																				52,
																				Short.MAX_VALUE)
																		.addComponent(
																				jTextFieldFreePort,
																				GroupLayout.PREFERRED_SIZE,
																				77,
																				GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		jPanelHostGameLayout
				.setVerticalGroup(jPanelHostGameLayout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelHostGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelHostGameLayout
														.createParallelGroup(
																GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabelHostGame)
														.addComponent(
																jRadioButtonHostGame))
										.addGap(25, 25, 25)
										.addGroup(
												jPanelHostGameLayout
														.createParallelGroup(
																GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabelFreePort)
														.addComponent(
																jTextFieldFreePort,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addContainerGap(52, Short.MAX_VALUE)));

		GroupLayout jPanelJoinGameLayout = new GroupLayout(jPanelJoinGame);
		jPanelJoinGame.setLayout(jPanelJoinGameLayout);
		jPanelJoinGameLayout
				.setHorizontalGroup(jPanelJoinGameLayout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelJoinGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelJoinGameLayout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelJoinGameLayout
																		.createSequentialGroup()
																		.addGroup(
																				jPanelJoinGameLayout
																						.createParallelGroup(
																								GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabelSharedPort)
																						.addComponent(
																								jLabeIPAddress))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				jPanelJoinGameLayout
																						.createParallelGroup(
																								GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextFieldIPAddress,
																								GroupLayout.DEFAULT_SIZE,
																								84,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextFieldSharedPort,
																								GroupLayout.DEFAULT_SIZE,
																								84,
																								Short.MAX_VALUE)))
														.addGroup(
																jPanelJoinGameLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabelJoinGame)
																		.addGap(29,
																				29,
																				29)
																		.addComponent(
																				jRadioButtonJoinGame)))
										.addContainerGap()));
		jPanelJoinGameLayout
				.setVerticalGroup(jPanelJoinGameLayout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelJoinGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelJoinGameLayout
														.createParallelGroup(
																GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabelJoinGame)
														.addComponent(
																jRadioButtonJoinGame,
																GroupLayout.PREFERRED_SIZE,
																21,
																GroupLayout.PREFERRED_SIZE))
										.addGap(25, 25, 25)
										.addGroup(
												jPanelJoinGameLayout
														.createParallelGroup(
																GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabelSharedPort)
														.addComponent(
																jTextFieldSharedPort,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanelJoinGameLayout
														.createParallelGroup(
																GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabeIPAddress)
														.addComponent(
																jTextFieldIPAddress,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		GroupLayout jPanelHostOrJoinGameLayout = new GroupLayout(
				jPanelHostOrJoinGame);
		jPanelHostOrJoinGame.setLayout(jPanelHostOrJoinGameLayout);
		jPanelHostOrJoinGameLayout
				.setHorizontalGroup(jPanelHostOrJoinGameLayout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelHostOrJoinGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelHostOrJoinGameLayout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanelHostOrJoinGameLayout
																		.createSequentialGroup()
																		.addComponent(
																				jPanelHostGame,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jPanelJoinGame,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jLabelHostOrJoinGame))
										.addContainerGap(
												GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanelHostOrJoinGameLayout
				.setVerticalGroup(jPanelHostOrJoinGameLayout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								GroupLayout.Alignment.TRAILING,
								jPanelHostOrJoinGameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabelHostOrJoinGame)
										.addGap(18, 18, 18)
										.addGroup(
												jPanelHostOrJoinGameLayout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanelHostGame,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanelJoinGame,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));

		GroupLayout jPanelEnterYourNameLayout = new GroupLayout(
				jPanelEnterYourName);
		jPanelEnterYourName.setLayout(jPanelEnterYourNameLayout);
		jPanelEnterYourNameLayout
				.setHorizontalGroup(jPanelEnterYourNameLayout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelEnterYourNameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanelEnterYourNameLayout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabelEnterYourName)
														.addGroup(
																jPanelEnterYourNameLayout
																		.createSequentialGroup()
																		.addComponent(
																				jLabelPlayerName)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jTextPlayerName,
																				GroupLayout.PREFERRED_SIZE,
																				113,
																				GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(249, Short.MAX_VALUE)));
		jPanelEnterYourNameLayout
				.setVerticalGroup(jPanelEnterYourNameLayout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanelEnterYourNameLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabelEnterYourName)
										.addGap(18, 18, 18)
										.addGroup(
												jPanelEnterYourNameLayout
														.createParallelGroup(
																GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabelPlayerName)
														.addComponent(
																jTextPlayerName,
																GroupLayout.PREFERRED_SIZE,
																20,
																GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(20, 20,
																		20)
																.addComponent(
																		jLabelStep1of2))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						jPanelEnterYourName,
																						GroupLayout.Alignment.LEADING,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jPanelHostOrJoinGame,
																						GroupLayout.Alignment.LEADING,
																						GroupLayout.DEFAULT_SIZE,
																						GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)))
												.addGroup(
														GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jButtonConnect,
																		GroupLayout.DEFAULT_SIZE,
																		214,
																		Short.MAX_VALUE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButtonCancel,
																		GroupLayout.PREFERRED_SIZE,
																		229,
																		GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabelStatus)))
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabelStep1of2)
						.addGap(18, 18, 18)
						.addComponent(jPanelEnterYourName,
								GroupLayout.PREFERRED_SIZE,
								GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jPanelHostOrJoinGame,
								GroupLayout.PREFERRED_SIZE,
								GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jLabelStatus)
						.addGap(18, 18, 18)
						.addGroup(
								layout.createParallelGroup(
										GroupLayout.Alignment.BASELINE)
										.addComponent(jButtonConnect)
										.addComponent(jButtonCancel))
						.addContainerGap(GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jRadioButtonHostGameActionPerformed(ActionEvent evt) {
		jRadioButtonJoinGame.setSelected(false);
		jRadioButtonHostGame.setSelected(true);

		jTextFieldFreePort.setEnabled(true);
		jTextFieldIPAddress.setEnabled(false);
		jTextFieldSharedPort.setEnabled(false);
	}

	private void jRadioButtonJoinGameActionPerformed(ActionEvent evt) {
		jRadioButtonHostGame.setSelected(false);
		jRadioButtonJoinGame.setSelected(true);

		jTextFieldFreePort.setEnabled(false);
		jTextFieldIPAddress.setEnabled(true);
		jTextFieldSharedPort.setEnabled(true);
	}

	private void jButtonCancelActionPerformed(ActionEvent evt) {
		System.exit(0);
	}

	private void jButtonConnectActionPerformed(ActionEvent evt) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		if (jRadioButtonHostGame.isSelected()) {
			final int port = Integer.parseInt(jTextFieldFreePort.getText());
			Game g = new Game();
			g.hostGame(port);
			this.dispose();
		} else if (jRadioButtonJoinGame.isSelected()) {
			final int port = Integer.parseInt(jTextFieldSharedPort.getText());
			final String IP = jTextFieldIPAddress.getText();
			Game g = new Game();
			g.joinGame(port, IP);
			this.dispose();
		}
	}
}
